### ISSUE TITLE
NPM not loading

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb-storybook#4]
after `npm install`

```bash
npm WARN react-addons-perf@15.3.0 requires a peer of react@^15.3.0 but none was installed.
npm WARN react-addons-shallow-compare@15.3.0 requires a peer of react@^15.3.0 but none was installed.
npm WARN react-stonecutter@0.3.3 requires a peer of react@^15.3.0 but none was installed.
npm WARN react-stonecutter@0.3.3 requires a peer of react-dom@^15.3.0 but none was installed.
npm WARN react-infinite@0.9.2 requires a peer of react@^15.0.0 but none was installed.
npm WARN react-infinite@0.9.2 requires a peer of react-dom@^15.0.0 but none was installed.
npm WARN material-ui@0.15.4 requires a peer of react@^15.0.0 but none was installed.
npm WARN material-ui@0.15.4 requires a peer of react-dom@^15.0.0 but none was installed.
npm WARN material-ui@0.15.4 requires a peer of react-tap-event-plugin@^1.0.0 but none was installed.
npm WARN react-addons-create-fragment@15.3.0 requires a peer of react@^15.3.0 but none was installed.
npm WARN react-addons-transition-group@15.3.0 requires a peer of react@^15.3.0 but none was installed.
npm WARN react-addons-test-utils@15.3.0 requires a peer of react@^15.3.0 but none was installed.
```

after `npm run storybook`

```bash
arthursoares@Arthur Soares:~/Sites/tdb-storybook|master
⇒  npm run storybook

> react-hot-boilerplate@1.0.0 storybook /Users/arthursoares/Sites/tdb-storybook
> start-storybook -p 9001

=> Loading custom .babelrc
=> Loading custom webpack config.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::9001
    at Object.exports._errnoException (util.js:953:11)
    at exports._exceptionWithHostPort (util.js:976:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1385:5)
    at EventEmitter.listen (/Users/arthursoares/Sites/tdb-storybook/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/Users/arthursoares/Sites/tdb-storybook/node_modules/@kadira/storybook/dist/server/index.js:68:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.2.0/bin/node" "/usr/local/bin/npm" "run" "storybook"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! react-hot-boilerplate@1.0.0 storybook: `start-storybook -p 9001`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-hot-boilerplate@1.0.0 storybook script 'start-storybook -p 9001'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-hot-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     start-storybook -p 9001
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-hot-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-hot-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/arthursoares/Sites/tdb-storybook/npm-debug.log```

**Comment by rafaelcorreiapoli** [comment]
Please be sure to have no other applications listening on port 9001
